name: tip012

on:
  push:
    branches:
      - main
    paths:
      - 'tip012/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11' # 必要に応じてJavaのバージョンを変更

    #- name: change directory to tip012
    #  run: pwd ; cd tip012 ; pwd

    - name: Install dependencies and run tests
      run: cd tip012 ; pwd ; gradle clean test --info
